name: wasm

on: [push, pull_request]
env:
  ONNXSIM_CI: 1

jobs:
  build_wasm:
    name: Build WebAssembly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: init
    - uses: mymindstorm/setup-emsdk@v11
    - uses: seanmiddleditch/gha-setup-ninja@v3
    - name: Verify
      run: emcc -v

    - name: Build
      run: ./build_wasm.sh

    - uses: actions/upload-artifact@v3
      with:
        name: wasm
        path: |
          build-wasm-node-OFF/onnxsim.js
          build-wasm-node-OFF/onnxsim.wasm
